### PR TITLE
Add Github actions

### PR DESCRIPTION
**Pull request by Jimver**
I wanted to learn GitHub Actions for a while and this seemed like a nice project to try it out on. 
I made two workflows:
- `main.yml` : On every push and pull request to master, GitHub actions creates the executable
- `release.yml`: When a release is created, a zip file with the .exe is automatically uploaded to the corresponding release! (See the releases at my fork for how it looks: https://github.com/Jimver/A32NX-installer/releases)

I also added a `requirements.txt` file for easier dependency installation.

### CODE REVIEW

**Comment by Externoak** [comment]
Thanks for the PR. 

Nice of you doing the requirements.txt file didn't get a chance to do it yet.

Just a small issue depending how the .exe is generated it can cause false AV flags in your case it gets flagged 6 times [Virustotal Scan](https://www.virustotal.com/gui/file/251bfa0b988f90f8ddde82f8b9b1037206364f298a2407f7ac3a3a07231c27cb/detection)
 when the current release version only gets flagged 2 (acceptable). Please check that the generated .exe does not get more false flags.

Hint: check that python version running is 64-bit version although it could be another reason.

**Comment by Jimver** [comment]
It should be x64 Python by default, I'll try what this stackoverflow answer mentioned: https://stackoverflow.com/a/52054580

**Comment by Jimver** [comment]
@Externoak I managed to get it to 2 warnings on [virustotal](https://www.virustotal.com/gui/file/ecafb33f5b62ff3795823df45b4fa4dc77805cb52b33322758a3d68a912a0864/detection) now using the answer from stackoverflow! See my [latest release](https://github.com/Jimver/A32NX-installer/releases/tag/v0.7.7).

Note that I removed pyinstaller from the requirements.txt as it should be installed manually after [building the bootloader](https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html). Instructions for that are in the readme.

**Comment by Externoak** [comment]
LGTM, Nice work.

**Pull request merged**
